services:
  db:
    image: postgres:17
    container_name: taskmanager-db
    environment:
      POSTGRES_DB: taskmanager_db
      POSTGRES_USER: sheinks
      POSTGRES_PASSWORD: your_password_here
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskmanager-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskmanager_db
      SPRING_DATASOURCE_USERNAME: sheinks
      SPRING_DATASOURCE_PASSWORD: Dullah10
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_OPEN_IN_VIEW: "false"
    ports:
      - "8080:8080"

volumes:
  postgres_data:
